### ISSUE TITLE
DBM - Dragon Soul

### ISSUE THREAD

**Issue by godgift17** [DeadlyBossMods/DBM-Cataclysm#16]
Hello,
Dragon Soul - Spine of Deathwing. countdown timer is wrong

**Comment by artazika** [comment]
I noticed this too today
barrel timer increased by about 10 seconds

**Comment by MysticalOS** [comment]
by an additional 10 seconds? it takes 20 seconds to roll now?

**Comment by artazika** [comment]
yep, the time between the announcement that he is going to do barrel roll and actually barrel roll it's 20 seconds. I just checked the announcements in the chat, exactly 20 seconds
