### ISSUE TITLE
Cata - DBM-Core.lua:7549:  Error

### ISSUE THREAD

**Issue by evilgodly** [DeadlyBossMods/DBM-Cataclysm#27]
**Describe the bug**
got this sometime tonight in BWD, unknown what caused it. 

**Do you have an error log of what happened?**
1x DBM-Core/DBM-Core.lua:7549: attempt to index field '?' (a nil value)
[string "@DBM-Core/DBM-Core.lua"]:7549: in function `GetRoleFlagValue'
[string "@DBM-Core/DBM-Core.lua"]:3126: in function `LoadModOptions'
[string "@DBM-Core/DBM-Core.lua"]:3239: in function `SpecChanged'
[string "@DBM-Core/DBM-Core.lua"]:3651: in function `func'
[string "@DBM-Core/modules/Scheduler.lua"]:163: in function <DBM-Core/modules/Scheduler.lua:153>

Locals:
self = <table> {
 stats = <table> {
 }
 SPELL_SUMMON = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:139
 SPELL_AURA_REMOVED = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:88
 isTrashMod = false
 numBoss = 1
 modId = "DBM-Raids-Cata"
 revision = 20240412064728
 yells = <table> {
 }
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 OnCombatStart = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:54
 isDummyMod = false
 encounterId = 1292
 localization = <table> {
 }
 announces = <table> {
 }
 subTab = 1
 NoSortAnnounce = false
 timers = <table> {
 }
 specwarns = <table> {
 }
 instanceId = 187
 modelId = 39094
 SPELL_MISSED = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:205
 SPELL_DAMAGE = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:205
 groupSpells = <table> {
 }
 combatInfo = <table> {
 }
 SPELL_CAST_START = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:106
 SPELL_AURA_APPLIED_DOSE = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:73
 zones = <table> {
 }
 statTypes = "normal,normal25,heroic,heroic25,lfr"
 Options = <table> {
 }
 SPELL_AURA_APPLIED = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:73
 addon = <table> {
 }
 OnCombatEnd = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:66
 categorySort = <table> {
 }
 optionCategories = <table> {
 }
 SyncThreshold = 8
 groupOptions = <table> {
 }
 SPELL_CAST_SUCCESS = <function> defined @DBM-Raids-Cata/DragonSoul/Morchok.lua:184
 creatureId = 55265
 id = "311"
 inCombat = false
 vb = <table> {
 }
 inCombatOnlyEvents = <table> {
 }
}
flag = "Tank"
flags = <table> {
 1 = "Tank"
}
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
flagText = "Tank"
(*temporary) = nil
(*temporary) = 251
(*temporary) = "^-"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
currentSpecID = 251
DBM = <table> {
 MoveSpecialWarning = <function> defined @DBM-Core/modules/objects/SpecialWarning.lua:132
 CopyAllModOption = <function> defined @DBM-Core/DBM-Core.lua:3328
 PLAY_MOVIE = <function> defined @DBM-Core/DBM-Core.lua:7435
 SortByTankAlpha = <function> defined @DBM-Core/DBM-Core.lua:7701
 CopyProfile = <function> defined @DBM-Core/DBM-Core.lua:2061
 GetNumRealGroupMembers = <function> defined @DBM-Core/DBM-Core.lua:2899
 CHAT_MSG_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:7096
 GetCachedBossHealth = <function> defined @DBM-Core/DBM-Core.lua:8090
 DungeonMusic = <table> {
 }
 FireEvent = <function> defined @DBM-Core/DBM-Core.lua:1969
 CreateModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:104
 GetMyPlayerInfo = <function> defined @DBM-Core/DBM-Core.lua:2805
 ADDON_LOADED = <function> defined @DBM-Core/DBM-Core.lua:1570
 CANCEL_PLAYER_COUNTDOWN = <function> defined @DBM-Core/DBM-Core.lua:5082
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core/DBM-Core.lua:2605
 AddDefeatSound = <function> defined @DBM-Core/modules/Sounds.lua:133
 GetDefeatSounds = <function> defined @DBM-Core/modules/Sounds.lua:126
 GroupInCombat = <function> defined @DBM-Core/DBM-Core.lua:8839
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core/DBM-Core.lua:4169
 GetSpellCooldown = <function> defined @DBM-Core/DBM-Core.lua:6620
 UPDATE_BATTLEFIELD_STATUS = <function> defined @DBM-Core/DBM-Core.lua:3700
 UnitAura = <function> defined @DBM-Core/DBM-Core.lua:6647
 IsRanged = <function> defined @DBM-Core/DBM-Core.lua:7643
 LFG_PROPOSAL_SHOW = <function> defined @DBM-Core/DBM-Core.lua:3607
 Rel

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
what class and spec?

**Comment by evilgodly** [comment]
NE 85 Frost DK

**Comment by MysticalOS** [comment]
were you in middle of respecting and spending talent points or something? basically at time of that error your spec info was missing from the game. in these situations DBM uses a fallback spec, but it was busted specifically for DKs (the fallback spec if your current spec was unreadable).

but still want to find out why your current spec was unreadable.
